apiVersion: v1
kind: PersistentVolume
metadata:
  name: fts
  labels:
    app: fts
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: fts
