kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: fts
