apiVersion: v1
kind: Service
metadata:
  name: fts
spec:
  type: ClusterIP
  selector:
    name: fts
  ports:
  - name: transaction
    port: 9200
    targetPort: 9200
  - name: cluster
    port: 9300
    targetPort: 9300
