version: '3'
services:
  rdb:
    image: 'postgres:10.1'
    ports:
      - '5456:5432'
    environment:
      POSTGRES_PASSWORD: 'p@ssw0rd'
      POSTGRES_USER: 'front.web'
      POSTGRES_DB: 'front.web'
    volumes:
      - rdb-data:/var/lib/postgresql/data
volumes:
  rdb-data:
