version: '3'
services:
  search:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.1.2'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      'discovery.type': 'single-node'
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
    driver: local
