apiVersion: v1
kind: PersistentVolume
metadata:
  name: rdb
  labels:
    app: rdb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: rdb
