kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: rdb
